# Generated by Django 5.2.7 on 2025-10-27 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('make', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('current_mileage', models.IntegerField(default=0, verbose_name='Quilometragem Atual')),
                ('maintenance_interval_km', models.IntegerField(default=10000, verbose_name='Intervalo de Revisão (KM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('mileage', models.IntegerField(verbose_name='Quilometragem Registrada')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_logs', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_records', to='core.vehicle', verbose_name='Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PRE', 'Preventiva'), ('COR', 'Corretiva')], max_length=3, verbose_name='Tipo de Manutenção')),
                ('date', models.DateField(verbose_name='Data da Manutenção')),
                ('description', models.TextField(verbose_name='Descrição do Serviço')),
                ('mileage_at_maintenance', models.IntegerField(verbose_name='KM no momento da Manutenção')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo das Peças')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Mão de Obra')),
                ('responsible_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mecânico Responsável')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.vehicle', verbose_name='Veículo')),
            ],
        ),
    ]
