# Generated by Django 5.2.7 on 2025-10-28 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Custo Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='mileage_at_maintenance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM no momento da Manutenção'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Custo das Peças'),
        ),
        migrations.AlterField(
            model_name='mileagerecord',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quilometragem Registrada'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quilometragem Atual'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='maintenance_interval_km',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervalo de Revisão (KM)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ano de Fabricação'),
        ),
    ]
